### ISSUE TITLE
Suggestion to unyank version 0.3.2

### ISSUE THREAD

**Issue by BinAlyan** [bodil/sized-chunks#20]
sized-chunks version 0.3.1 panic since rustc version 1.48.0, this cause issues on older packages which depend on it.

Example of backtrace in package cargo-real-deps:
```
thread 'main' panicked at 'attempted to zero-initialize type `sized_chunks::sized_chunk::Chunk<(core::package_id::PackageId, im_rc::OrdMap<core::package_id::PackageId, std::vec::Vec<core::dependency::Dependency>>)>`, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:622:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::mem::zeroed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:622
   4: sized_chunks::sized_chunk::Chunk<A,N>::new
             at ./vendor/sized-chunks/src/sized_chunk.rs:143
   5: <im_rc::nodes::btree::Node<A> as core::default::Default>::default
             at ./vendor/im-rc/./src/nodes/btree.rs:90
   6: im_rc::nodes::btree::Node<A>::new
             at ./vendor/im-rc/./src/nodes/btree.rs:114
   7: im_rc::ord::map::OrdMap<K,V>::new
             at ./vendor/im-rc/./src/ord/map.rs:173
   8: cargo::util::graph::Graph<N,E>::new
             at ./vendor/cargo/src/cargo/util/graph.rs:14
   9: cargo::core::resolver::encode::EncodableResolve::into_resolve
             at ./vendor/cargo/src/cargo/core/resolver/encode.rs:81
  10: cargo::ops::lockfile::load_pkg_lockfile::{{closure}}
             at ./vendor/cargo/src/cargo/ops/lockfile.rs:26
  11: cargo::ops::lockfile::load_pkg_lockfile
             at ./vendor/cargo/src/cargo/ops/lockfile.rs:23
  12: cargo::ops::resolve::resolve_with_registry
             at ./vendor/cargo/src/cargo/ops/resolve.rs:114
  13: cargo::ops::resolve::resolve_ws_with_method
             at ./vendor/cargo/src/cargo/ops/resolve.rs:69
  14: cargo_real_deps::main
             at ./src/main.rs:65
  15: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
One of the listed compatibility notes of rustc version 1.48.0

`mem::uninitialized will now panic if any inner types inside a struct or enum disallow zero-initialization.`

sized-chunks 0.3.2 fixed the problem by using MaybeUninit (which was introduced at rustc 1.36), however it was yanked as it raised the minimum supported rustc version and was released as 0.4.0. 

I am not really sure but I believe unyanking the 0.3.2 version will reduce the fricition for more developers which use such packages with the recent compilers. It is likely that fewer users use older rustc (< rustc 1.36) in comparisons to users with recent rustc. (>=1.48.0).

Two instances of this problem are: [here](https://github.com/Geal/cargo-real-deps/issues/4#issuecomment-787127505) and [here](https://github.com/meta-rust/cargo-bitbake/issues/22).

**Comment by kornelski** [comment]
This is a very very old version. You shouldn't be using 0.3 anyway. The current version is 0.6, and we've recently had a release for a soundness issue, so you should really upgrade to the latest.
